# Server
server.port=${PORT:8080}

# App
spring.application.name=movilidad-backend

# Datasource (local por defecto; se sobreescribe con variables de entorno)
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:movilidad}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Kafka
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=movilidad-backend

# Seguridad (JWT y modo local) CAMBIAR A FALSE SI NO SE QUIERE EN LOCAL
security.local.enabled=true  
security.jwt.jwk-set-uri=${AUTH_JWK_SET_URI:http://localhost:9000/.well-known/jwks.json}

# Actuator
management.endpoints.web.exposure.include=health,info

# springdoc-openapi
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
